### ISSUE TITLE
productionMode not working in RC1

### ISSUE THREAD

**Issue by scan2invoice** [devsoap/gradle-vaadin-flow#147]
When setting productionMode to true, the frontend-es5 and frontend-es6 folders are not generated. I used Gradle 5 and version 1.0.0.RC1 of the plugin. 

To reproduce set productionMode to true in the beverage starter example:
https://github.com/devsoap/examples/tree/master/beverage-starter-flow-gradle

Here is the error I get:

    FAILURE: Build failed with an exception.
    * What went wrong:
    Some problems were found with the configuration of task ':vaadinAssembleClient'.
    > Directory 'D:\proj\beverage-starter-flow-gradle\build\frontend\build\frontend-es5' specified for property '$1' does not exist.
    > Directory 'D:\proj\beverage-starter-flow-gradle\build\frontend\build\frontend-es6' specified for property '$2' does not exist.

**Comment by johndevs** [comment]
That could mean that something went wrong with the compilation step. Could you run it again with ``--info``? It should give you a more detailed log.

**Comment by johndevs** [comment]
Also, since you appear to be on Windows, there was some fixes regarding that in RC2, so maybe update to that as well.

**Comment by scan2invoice** [comment]
I upgraded to RC2 but I get he same issue. Please see the output of the run with --info
```

$ ./gradlew --info clean jar
Removing daemon from the registry due to communication failure. Daemon information: DaemonInfo{pid=17148, address=[68fd9b36-dc28-493e-889f-5fae0087f3f1 port:64539, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1541546583755, context=DefaultDaemonContext[uid=18f251fd-da18-40cf-83e6-4a064bb37906,javaHome=D:\programs\win\Java\jdk1.8.0_152,daemonRegistryDir=C:\Users\bjoern\.gradle\daemon,pid=17148,idleTimeout=10800000,priority=NORMAL,daemonOpts=-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=AU,-Duser.language=en,-Duser.variant]}
Waiting for daemons with canceled builds to become available
Removing 0 daemon stop events from registry
Previous Daemon (17148) stopped at Wed Nov 07 09:27:25 AEST 2018 by user or operating system
Starting a Gradle Daemon, 1 busy and 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
Starting process 'Gradle build daemon'. Working directory: C:\Users\bjoern\.gradle\daemon\5.0-rc-1 Command: D:\programs\win\Java\jdk1.8.0_152\bin\java.exe -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xmx512m -Dfile.encoding=windows-1252 -Duser.country=AU -Duser.language=en -Duser.variant -cp C:\Users\bjoern\.gradle\wrapper\dists\gradle-5.0-rc-1-bin\8qxzfuib1d4lt87td537k3z43\gradle-5.0-rc-1\lib\gradle-launcher-5.0.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.0-rc-1
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 12.847 secs.
The client will now receive all logging from the daemon (pid: 568). The daemon log file: C:\Users\bjoern\.gradle\daemon\5.0-rc-1\daemon-568.out.log
Starting build in new daemon [memory: 477.6 MB]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file 'D:\proj\beverage-starter-flow-gradle\settings.gradle'.
Projects loaded. Root project using build file 'D:\proj\beverage-starter-flow-gradle\build.gradle'.
Included projects: [root project 'beveragebuddy']

> Configure project :
Evaluating root project 'beveragebuddy' using build file 'D:\proj\beverage-starter-flow-gradle\build.gradle'.
Applying NodePluginAction_Decorated actions to project beveragebuddy
Configuring node extension for vaadin project
Applying GrettyPluginAction_Decorated actions to project beveragebuddy
Applying VaadinFlowPluginAction_Decorated actions to project beveragebuddy
Applying WarPluginAction_Decorated actions to project beveragebuddy
Using Gradle Vaadin Flow Plugin 1.0.0-RC2
All projects evaluated.
Selected primary task 'clean' from project :
Selected primary task 'jar' from project :
Tasks to be executed: [task ':clean', task ':compileJava', task ':vaadinConvertStyleCssToHtml', task ':nodeSetup', task ':yarnSetup', task ':vaadinInstallYarnDependencies', task ':vaadinInstallBowerDependencies', task ':vaadinConvertGroovyTemplatesToHtml', task ':vaadinTranspileDependencies', task ':vaadinAssembleClient', task ':vaadinPluginVersionCheck', task ':processResources', task ':classes', task ':jar']
:clean (Thread[Daemon worker,5,main]) started.

> Task :clean
Task ':clean' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:clean (Thread[Daemon worker,5,main]) completed. Took 0.127 secs.
:compileJava (Thread[Execution worker for ':',5,main]) started.

> Task :compileJava
Task ':compileJava' is not up-to-date because:
  Output property 'destinationDir' file D:\proj\beverage-starter-flow-gradle\build\classes\java\main has been removed.
  Output property 'destinationDir' file D:\proj\beverage-starter-flow-gradle\build\classes\java\main\com has been removed.
  Output property 'destinationDir' file D:\proj\beverage-starter-flow-gradle\build\classes\java\main\com\vaadin has been removed.
All input files are considered out-of-date for incremental task ':compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
Created classpath snapshot for incremental compilation in 0.131 secs.
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 13.604 secs.
:vaadinConvertStyleCssToHtml (Thread[Execution worker for ':',5,main]) started.

> Task :vaadinConvertStyleCssToHtml
Task ':vaadinConvertStyleCssToHtml' is not up-to-date because:
  Output property 'targetPath' file D:\proj\beverage-starter-flow-gradle\build\webapp-gen\frontend\styles has been removed.
:vaadinConvertStyleCssToHtml (Thread[Execution worker for ':',5,main]) completed. Took 0.031 secs.
:nodeSetup (Thread[Execution worker for ':',5,main]) started.

> Task :nodeSetup UP-TO-DATE
Skipping task ':nodeSetup' as it is up-to-date.
:nodeSetup (Thread[Execution worker for ':',5,main]) completed. Took 2.691 secs.
:yarnSetup (Thread[Execution worker for ':',5,main]) started.

> Task :yarnSetup UP-TO-DATE
Skipping task ':yarnSetup' as it is up-to-date.
:yarnSetup (Thread[Execution worker for ':',5,main]) completed. Took 0.013 secs.
:vaadinInstallYarnDependencies (Thread[Execution worker for ':',5,main]) started.

> Task :vaadinInstallYarnDependencies
Task ':vaadinInstallYarnDependencies' is not up-to-date because:
  Task ':vaadinInstallYarnDependencies' class path has changed from a2470531c7696b04ad293c2f7a604e17 to 64ad3c827ce8616e90d62d73c14bb345.
Creating package.json ...
Writing template .yarnrc to D:\proj\beverage-starter-flow-gradle\build\frontend\.yarnrc
Starting process 'command 'D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd''. Working directory: D:\proj\beverage-starter-flow-gradle\build\frontend Command: D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd --prefer-offline init -y
Successfully started process 'command 'D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd''
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.


Extracting webjars...
Installing yarn dependencies...
Starting process 'command 'D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd''. Working directory: D:\proj\beverage-starter-flow-gradle\build\frontend Command: D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd --prefer-offline --no-bin-links install
Successfully started process 'command 'D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd''
warning polymer-cli > bower@1.8.2: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/


warning polymer-cli > github@7.3.2: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)


warning polymer-cli > polymer-project-config > plylog > @types/winston@2.4.4: This is a stub types definition. winston provides its own type definitions, so you do not need this installed.


warning polymer-cli > web-component-tester > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.


warning polymer-cli > web-component-tester > sinon > formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead


warning polymer-cli > web-component-tester > sinon > text-encoding@0.6.4: no longer maintained


warning polymer-cli > web-component-tester > wd > request > hawk > boom@4.3.1: This version is no longer maintained. Please upgrade to the latest version.


warning bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/


warning "polymer-cli > web-component-tester > sinon-chai@2.14.0" has unmet peer dependency "chai@>=1.9.2 <5".


:vaadinInstallYarnDependencies (Thread[Execution worker for ':',5,main]) completed. Took 9 mins 53.271 secs.
:vaadinInstallBowerDependencies (Thread[Execution worker for ':',5,main]) started.

> Task :vaadinInstallBowerDependencies
Task ':vaadinInstallBowerDependencies' is not up-to-date because:
  Task ':vaadinInstallBowerDependencies' class path has changed from a2470531c7696b04ad293c2f7a604e17 to 64ad3c827ce8616e90d62d73c14bb345.
Extracting webjars...
Unpacking frontend resources in vaadin-iron-list-flow-1.0.4.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\static
Undpacking frontend component in webcomponentsjs-1.2.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\webcomponentsjs
Undpacking frontend component in shadycss-1.2.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\shadycss
Undpacking frontend component in polymer-2.6.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\polymer
Undpacking frontend component in iron-resizable-behavior-2.1.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-resizable-behavior
Undpacking frontend component in iron-scroll-target-behavior-2.1.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-scroll-target-behavior
Undpacking frontend component in iron-a11y-keys-behavior-2.1.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-a11y-keys-behavior
Undpacking frontend component in iron-list-2.0.17.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-list
Undpacking frontend component in iron-meta-2.1.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-meta
Undpacking frontend component in iron-iconset-svg-2.2.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-iconset-svg
Undpacking frontend component in iron-flex-layout-2.0.3.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-flex-layout
Undpacking frontend component in iron-icon-2.1.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-icon
Undpacking frontend component in vaadin-icons-4.1.4.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-icons
Undpacking frontend component in vaadin-lumo-styles-1.0.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-lumo-styles
Unpacking frontend resources in flow-data-1.0.5.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\static
Undpacking frontend component in vaadin-themable-mixin-1.1.6.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-themable-mixin
Undpacking frontend component in vaadin-development-mode-detector-1.0.3.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-development-mode-detector
Undpacking frontend component in vaadin-usage-statistics-1.0.0-optout.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-usage-statistics
Undpacking frontend component in vaadin-element-mixin-1.0.2.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-element-mixin
Undpacking frontend component in vaadin-notification-1.0.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-notification
Undpacking frontend component in vaadin-control-state-mixin-2.0.3.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-control-state-mixin
Undpacking frontend component in vaadin-progress-bar-1.0.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-progress-bar
Undpacking frontend component in vaadin-button-2.0.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-button
Undpacking frontend component in vaadin-upload-4.0.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-upload
Unpacking frontend resources in vaadin-text-field-flow-1.0.4.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\static
Undpacking frontend component in vaadin-text-field-2.0.2.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-text-field
Undpacking frontend component in vaadin-list-mixin-2.0.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-list-mixin
Undpacking frontend component in vaadin-item-2.0.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-item
Undpacking frontend component in vaadin-tabs-2.0.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-tabs
Undpacking frontend component in vaadin-split-layout-4.0.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-split-layout
Undpacking frontend component in vaadin-radio-button-1.0.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-radio-button
Undpacking frontend component in vaadin-ordered-layout-1.0.2.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-ordered-layout
Undpacking frontend component in vaadin-list-box-1.0.3.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-list-box
Unpacking frontend resources in vaadin-grid-flow-1.0.5.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\static
Undpacking frontend component in iron-a11y-announcer-2.1.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-a11y-announcer
Undpacking frontend component in vaadin-checkbox-2.1.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-checkbox
Undpacking frontend component in vaadin-grid-5.0.4.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-grid
Undpacking frontend component in vaadin-form-layout-2.0.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-form-layout
Undpacking frontend component in iron-fit-behavior-2.2.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-fit-behavior
Undpacking frontend component in iron-overlay-behavior-2.3.4.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-overlay-behavior
Undpacking frontend component in vaadin-overlay-3.0.3.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-overlay
Undpacking frontend component in vaadin-dialog-2.0.2.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-dialog
Unpacking frontend resources in vaadin-date-picker-flow-1.0.6.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\static
Undpacking frontend component in iron-media-query-2.1.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\iron-media-query
Undpacking frontend component in vaadin-date-picker-3.0.3.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-date-picker
Undpacking frontend component in vaadin-combo-box-4.0.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-combo-box
Undpacking frontend component in cookieconsent-3.0.6.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\cookieconsent
Undpacking frontend component in license-checker-2.0.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-license-checker
Undpacking frontend component in vaadin-cookie-consent-1.0.2.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-cookie-consent
Undpacking frontend component in vaadin-confirm-dialog-1.0.1.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-confirm-dialog
Undpacking frontend component in vaadin-charts-6.1.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\highcharts
Undpacking frontend component in vaadin-board-2.0.0.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-board
Undpacking frontend component in vaadin-usage-statistics-1.0.0-optout.jar into D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components\vaadin-usage-statistics
Creating bower.json...
Installing bower dependencies ...
Starting process 'command 'D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd''. Working directory: D:\proj\beverage-starter-flow-gradle\build\frontend Command: D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd --prefer-offline run bower install --config.interactive=false
Successfully started process 'command 'D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd''
:vaadinInstallBowerDependencies (Thread[Execution worker for ':',5,main]) completed. Took 14.565 secs.
:vaadinConvertGroovyTemplatesToHtml (Thread[Execution worker for ':',5,main]) started.

> Task :vaadinConvertGroovyTemplatesToHtml SKIPPED
Skipping task ':vaadinConvertGroovyTemplatesToHtml' as task onlyIf is false.
:vaadinConvertGroovyTemplatesToHtml (Thread[Execution worker for ':',5,main]) completed. Took 0.026 secs.
:vaadinTranspileDependencies (Thread[Execution worker for ':',5,main]) started.

> Task :vaadinTranspileDependencies
Task ':vaadinTranspileDependencies' is not up-to-date because:
  Task ':vaadinTranspileDependencies' class path has changed from a2470531c7696b04ad293c2f7a604e17 to 64ad3c827ce8616e90d62d73c14bb345.
Copying unpacked static resources
Copying generated styles....
Copying generated templates....
Copying html templates ...
Searching for HTML imports...
Searching for html imports in D:\proj\beverage-starter-flow-gradle\build\frontend\node_modules
Searching for html imports in D:\proj\beverage-starter-flow-gradle\build\frontend\bower_components
Searching for html imports in D:\proj\beverage-starter-flow-gradle\build\webapp-gen\frontend\styles
Searching for html imports in D:\proj\beverage-starter-flow-gradle\src\main\webapp\frontend\templates
Searching for resource HTML/JS imports in D:\proj\beverage-starter-flow-gradle\build\frontend
Creating vaadin-flow-bundle-5y8ihwxbgt8fm60b3z7dodxst.cache.html...
Creating polymer.json...
Creating vaadin-flow-bundle-manifest.json...
Starting process 'command 'D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd''. Working directory: D:\proj\beverage-starter-flow-gradle\build\frontend Command: D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd --prefer-offline run polymer-bundler --inline-scripts --manifest-out=D:\proj\beverage-starter-flow-gradle\build\frontend\vaadin-flow-bundle-manifest.json vaadin-flow-bundle-5y8ihwxbgt8fm60b3z7dodxst.cache.html
Successfully started process 'command 'D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd''
Transpiling...
Starting process 'command 'D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd''. Working directory: D:\proj\beverage-starter-flow-gradle\build\frontend Command: D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd --prefer-offline run polymer build --npm --module-resolution=node
Successfully started process 'command 'D:\proj\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.9.1\yarn.cmd''
:vaadinTranspileDependencies (Thread[Execution worker for ':',5,main]) completed. Took 1 mins 44.556 secs.
:vaadinAssembleClient (Thread[Execution worker for ':',5,main]) started.

> Task :vaadinAssembleClient FAILED
:vaadinAssembleClient (Thread[Execution worker for ':',5,main]) completed. Took 0.003 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':vaadinAssembleClient'.
> Directory 'D:\proj\beverage-starter-flow-gradle\build\frontend\build\frontend-es5' specified for property '$1' does not exist.
> Directory 'D:\proj\beverage-starter-flow-gradle\build\frontend\build\frontend-es6' specified for property '$2' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0-rc-1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13m 4s
9 actionable tasks: 7 executed, 2 up-to-date
```

**Comment by johndevs** [comment]
Looks like this is a result of multiple issues with polymer-cli:

https://github.com/Polymer/polymer-cli/issues/821 makes it so that the transpile step succeeds even if no transpile is done. Basically, polymer-cli seems to hide the issue.

Using the workaround mention in the above issue (adding ``--js-compile --js-minify --css-minify --html-minify`` to the ``polymer build`` command) reveals the real issue:
```
$ ./node_modules/polymer-cli/bin/polymer.js build --js-compile --js-minify --css-minify --html-minify
info:	Clearing build/ directory...
info:	(default) Building...
error:	Promise rejection: AssertionError [ERR_ASSERTION]: Trying to save already-saved file part "/home/john/Repositories/devsoap.com-examples/beverage-starter-flow-gradle/build/frontend/bower_components/polymer/lib/legacy/legacy-element-mixin.html_script_0.js".
error:	AssertionError [ERR_ASSERTION]: Trying to save already-saved file part "/home/john/Repositories/devsoap.com-examples/beverage-starter-flow-gradle/build/frontend/bower_components/polymer/lib/legacy/legacy-element-mixin.html_script_0.js".
    at SplitFile.setPartContent (/home/john/Repositories/devsoap.com-examples/beverage-starter-flow-gradle/build/frontend/node_modules/polymer-build/lib/html-splitter.js:142:9)
    at HtmlRejoinTransform._transformIter_2 (/home/john/Repositories/devsoap.com-examples/beverage-starter-flow-gradle/build/frontend/node_modules/polymer-build/lib/html-splitter.js:256:40)
    at _transformIter_2.next (<anonymous>)
    at resume (/home/john/Repositories/devsoap.com-examples/beverage-starter-flow-gradle/build/frontend/node_modules/polymer-build/lib/html-splitter.js:36:44)
    at fulfill (/home/john/Repositories/devsoap.com-examples/beverage-starter-flow-gradle/build/frontend/node_modules/polymer-build/lib/html-splitter.js:38:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This is basically the same issue as reported here https://github.com/Polymer/polymer-cli/issues/881

This also doesn't occur with all projects (tests are still green), so apparently something in the beverage starter is triggering this.

**Comment by johndevs** [comment]
Looks like the issue is with the ``reviews-list.html`` -template. 

You can work around the issue for now by removing the template and re-implementing the template in Java until the issues in my previous comment are resolved.
