### ISSUE TITLE
Error scanning entry module-info.class from byte-buddy-1.9.0.jar

### ISSUE THREAD

**Issue by johndevs** [devsoap/gradle-vaadin-flow#162]
**Desktop (please complete the following information):**
 - OS: Ubuntu
- JDK version: 11
 - Gradle version: 5.0.0
 - Vaadin Plugin version: 1.0.0.RC3

**Describe the bug**
Running **jettyRun** for project fails in the following exception:
```
java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/home/john/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.9.0/8cb0d5baae526c9df46ae17693bbba302640538b/byte-buddy-1.9.0.jar
        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913) ~[jetty-annotations-9.2.26.v20180806.jar:9.2.26.v20180806]
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:831) ~[jetty-annotations-9.2.26.v20180806.jar:9.2.26.v20180806]
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:164) ~[jetty-annotations-9.2.26.v20180806.jar:9.2.26.v20180806]
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:549) ~[jetty-annotations-9.2.26.v20180806.jar:9.2.26.v20180806]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) ~[jetty-util-9.2.26.v20180806.jar:9.2.26.v20180806]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) ~[jetty-util-9.2.26.v20180806.jar:9.2.26.v20180806]
        at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
```

**To Reproduce**
1. Setup example project from wiki
2. Use a snapshot version of Vaadin
2. Run **jettyRun** task
4. Exception is thrown

**Expected behavior**
The project runs

**Comment by johndevs** [comment]
This is not an issue with either Vaadin or the Vaadin plugin, this is due to the Gretty plugin pulling in a version of Jetty which tries to do an annotation scan on the JDK9 modules. 

The bug is further described in https://github.com/akhikhl/gretty/issues/360 and https://github.com/eclipse/jetty.project/issues/1692.

Workaround for 1.0.0.RC3:

Add this to **build.gradle**:
```
gretty {
    servletContainer = 'jetty9.4'
}
```
Add this to **gradle.properties**:
```
jetty94Version=9.4.12.v20180830
```
### This workaround is only needed for RC3 and will be done automatically from 1.0.0.RC4 and forward.

cc: @ripla
