### ISSUE TITLE
Only themes and styles folders are considered in production mode

### ISSUE THREAD

**Issue by alabotski** [devsoap/gradle-vaadin-flow#185]
**Build.gradle**
```
plugins {
    id 'org.gretty' version '2.3.1'
    id 'com.devsoap.vaadin-flow' version '1.0.0.RC6'
}

apply plugin: 'java'
apply plugin: 'war'

vaadin {
   version '12.0.0'
}

vaadin.autoconfigure()

repositories {
  // Add the pre-release repository
  vaadin.prereleases()
  // Add the addons repository
  vaadin.addons()
}

dependencies {
  implementation vaadin.bom()
  implementation vaadin.platform()
}
```

I build it in production mode = true

When deploy it on Tomcat 9.0.14 and try run I have such error

```
Type Exception Report

Message Servlet.init() for servlet [AaaServlet] threw exception

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: Servlet.init() for servlet [AaaServlet] threw exception
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)

Root Cause

java.lang.IllegalArgumentException: Failed to find the bundle manifest file 'frontend://vaadin-flow-bundle-manifest.json' in the servlet context for 'ES6' browsers. If you are running a dev-mode servlet container in maven e.g. `jetty:run` change it to `jetty:run-exploded`. If you are not compiling frontend resources, include the 'vaadin-maven-plugin' in your build script. Otherwise, you can skip this error either by disabling production mode, or by setting the servlet parameter 'original.frontend.resources=true'.
	com.vaadin.flow.server.startup.BundleFilterInitializer.readBundleManifest(BundleFilterInitializer.java:77)
	com.vaadin.flow.server.startup.BundleFilterInitializer.addBundleFilterForBrowser(BundleFilterInitializer.java:68)
	com.vaadin.flow.server.startup.BundleFilterInitializer.serviceInit(BundleFilterInitializer.java:62)
	com.vaadin.flow.server.VaadinService.lambda$init$0(VaadinService.java:258)
	java.util.Iterator.forEachRemaining(Iterator.java:116)
	java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	com.vaadin.flow.server.VaadinService.init(VaadinService.java:258)
	com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:186)
	com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:167)
	com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:71)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)

Note The full stack trace of the root cause is available in the server logs.
```

<img width="1680" alt="screen shot 2019-01-18 at 10 16 35" src="https://user-images.githubusercontent.com/439337/51371091-3091df80-1b0a-11e9-8686-a8f948ff1c0e.png">

**Comment by johndevs** [comment]
Hi,

Your example build file is working for me on Tomcat 9. 

A few things you could check:

1) Ensure you have  ``vaadin.productionMode=true`` or ``vaadin {  productionMode=true }`` in your **build.gradle** file
2) When running ``gradle war`` to generate the war ensure that both *vaadinTranspileDependencies* and *vaadinAssembleClient* tasks have run successfully.
3) Open up the war file and check if the files are there, there should be 3 frontend folders; _frontend_, _frontend-es5_ and _frontend-es6_.

**Comment by alabotski** [comment]
Hm I don't add such stirng

**vaadin.productionMode=true**

I only change this class
```

@WebServlet(urlPatterns = "/*", name = "AaaServlet", asyncSupported = true)
@VaadinServletConfiguration(ui = AaaUI.class, productionMode = true)
public class AaaServlet extends VaadinServlet { }
```

Ok thank you

**Comment by alabotski** [comment]
But in my project I have such error in production

```
Caused by: java.lang.IllegalStateException: Can't find resource 'frontend://src/views/main-view.html' via the servlet context
	at com.vaadin.flow.component.polymertemplate.DefaultTemplateParser.getTemplateContent(DefaultTemplateParser.java:105) ~[flow-server-1.2.2.jar:1.2.2]
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:187) ~[flow-server-1.2.2.jar:1.2.2]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.lambda$null$23ee5b4f$1(TemplateInitializer.java:89) ~[flow-server-1.2.2.jar:1.2.2]
	at com.vaadin.flow.internal.ReflectionCache.lambda$wrapValueProvider$d0062d93$1(ReflectionCache.java:84) ~[flow-server-1.2.2.jar:1.2.2]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_191]
	at com.vaadin.flow.internal.ReflectionCache.get(ReflectionCache.java:101) ~[flow-server-1.2.2.jar:1.2.2]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:90) ~[flow-server-1.2.2.jar:1.2.2]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:107) ~[flow-server-1.2.2.jar:1.2.2]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:122) ~[flow-server-1.2.2.jar:1.2.2]
	at test.project.ui.views.MainView.<init>(MainView.java:34) ~[classes/:na]
	... 43 common frames omitted
```

**Comment by alabotski** [comment]
Request

**http://localhost:8080/test-1.0-SNAPSHOT/frontend-es6/src/views/main-view.html**

**Comment by johndevs** [comment]
Templates need to be under the frontend folder so they get included in the client compilation. 

You can check out the example project https://github.com/devsoap/examples/tree/master/beverage-starter-flow-gradle and see how it has been done there.

**Comment by alabotski** [comment]
```
Execution failed for task ':vaadinTranspileDependencies'.
> Imported file '/Users/lesharb/Workspace/project/temp-ui/build/frontend/templates/components/forms/../../../styles/shared-styles.html' in templates/components/forms/signup-form.html does not exist!
```

**signup-form.html**
```
<link rel="import" href="../../../bower_components/polymer/polymer-element.html">
<link rel="import" href="../../../styles/shared-styles.html">

<img width="395" alt="image" src="https://user-images.githubusercontent.com/439337/51396180-a3717980-1b4f-11e9-99b6-07c6e97a13e7.png">

```

**Comment by alabotski** [comment]
I change 
`<link rel="import" href="../../../styles/shared-styles.html">`
on 
`@HtmlImport("frontend://styles/shared-styles.html")`

And all work well

**Comment by alabotski** [comment]
But now I have problem with

<link rel="import" href="../bower_components/polymer/lib/elements/custom-style.html">

404 Error
`
http://localhost:8080/test-enterprise-ui-1.0-SNAPSHOT/frontend-es6/bower_components/polymer/lib/elements/custom-style.html`

**Comment by alabotski** [comment]
FieldText in development mode has such structure

<img width="515" alt="image" src="https://user-images.githubusercontent.com/439337/51482206-dd888880-1da6-11e9-8b35-2eadb832098f.png">

But in production mode it has such structure

<img width="429" alt="image" src="https://user-images.githubusercontent.com/439337/51482491-a1095c80-1da7-11e9-9ae6-174864ba1836.png">

Why added 
**<style include="material-text-field"></style>**

**Comment by alabotski** [comment]
Can anybody help me?
With styles....


Production mode work with material style

**Comment by Robis1982** [comment]
There are really bug exist. When resounce located exactly in frontend folder (not in subfolders) and project compiled with production flag. In runtime there is error when you try point to this resource. If you put it one level deeper - all work fine... at least it's look like fine:)

**Comment by johndevs** [comment]
True, this is a bug. Only _themes_ and _styles_ folders in webapp are considered right now in production mode.
