### ISSUE TITLE
Failed to find the bundle manifest file

### ISSUE THREAD

**Issue by alabotski** [devsoap/gradle-vaadin-flow#194]
I try build in production mode last plugin version and have such error

```
06-Feb-2019 16:12:38.156 SEVERE [http-nio-8080-exec-16] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [SalesHeroServlet]
 java.lang.IllegalArgumentException: Failed to find bundle 'frontend://_missing', specified in manifest 'frontend://vaadin-flow-bundle-manifest.json'. Remove file reference from the manifest to disable bundle usage or add the bundle to the path specified.
	at com.vaadin.flow.server.startup.BundleFilterFactory.createDependencyFilter(BundleFilterFactory.java:118)
	at com.vaadin.flow.server.startup.BundleFilterFactory.lambda$createBundleFilterForBrowser$1(BundleFilterFactory.java:80)
	at java.util.Optional.flatMap(Optional.java:241)
	at com.vaadin.flow.server.startup.BundleFilterFactory.createBundleFilterForBrowser(BundleFilterFactory.java:80)
	at com.vaadin.flow.server.startup.BundleFilterFactory.createFilters(BundleFilterFactory.java:70)
	at com.vaadin.flow.server.VaadinService.init(VaadinService.java:267)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:201)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:182)
	at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:72)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1123)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1078)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by brp-oskar** [comment]
Look in the file `build/frontend/vaadin-flow-bundle-manifest.json`. It has a key that is named `_missing` that lists the missing files. You can exclude them with code like this in your `build.gradle`:
```
vaadinTranspileDependencies {
    bundleExcludes = ['https://www.gstatic.com/charts/loader.js']
}
```

**Comment by alabotski** [comment]
Thank for your advice
