### ISSUE TITLE
Support folder hierarchies in META-INF/resources/frontend/

### ISSUE THREAD

**Issue by johndevs** [devsoap/gradle-vaadin-flow#208]
In my case 'productionMode' doens't work for vaadin addons(https://github.com/appreciated/vaadin-app-layout) but debug mode is ok.

When i compile with productionMode, build file has 'frontend/com/github' and 'statric/com/github' but 'vaadin-flow-bundle-manifest.json' doens't have it.
The file also doesn't have 'frontend://_missing'.

Below is the error message for productionMode.

Caused by: java.lang.IllegalStateException: Can't find resource 'frontend://com/github/appreciated/app-layout/left/left-responsive-hybrid.html' via the servlet context
	at com.vaadin.flow.component.polymertemplate.DefaultTemplateParser.getTemplateContent(DefaultTemplateParser.java:105)
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:187)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.lambda$null$23ee5b4f$1(TemplateInitializer.java:89)
	at com.vaadin.flow.internal.ReflectionCache.lambda$wrapValueProvider$d0062d93$1(ReflectionCache.java:84)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.vaadin.flow.internal.ReflectionCache.get(ReflectionCache.java:101)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:90)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:107)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:122)
	at com.github.appreciated.app.layout.behaviour.AppLayout.<init>(AppLayout.java:10)
	at com.github.appreciated.app.layout.behaviour.AbstractLeftAppLayoutBase.<init>(AbstractLeftAppLayoutBase.java:46)
	at com.github.appreciated.app.layout.behaviour.LeftLayouts$LeftResponsiveHybrid.<init>(LeftLayouts.java:67)

_Originally posted by @corinara in https://github.com/devsoap/gradle-vaadin-flow/issues/207#issuecomment-466995910_

**Comment by corinara** [comment]
Hi John

It looks output of build directories are bit different between Maven and Gradle.
If the Vaadin addon doesn't have 'bower.json'

### Maven/target

- frontend/com/github
- [my-app]/frontend5/com/github
_vaadin-flow-bundle-manifest.json - has a com.github.XX_
- [my-app]/frontend6/com/github
_vaadin-flow-bundle-manifest.json - has a com.github.XX_

###  Gradle/build/
- frontend/com/github
- static/com/github
- resources/frontend5/**_NO-COM.GITHUB.XX_**
_vaadin-flow-bundle-manifest.json - donesn't have com.github.XX_
- resources/frontend6/_**NO-COM.GITHUB.XX**_
_vaadin-flow-bundle-manifest.json - donesn't have com.github.XX_

**Comment by johndevs** [comment]
Since in production mode the plugin will re-compile the addon from sources it needs to have either a bower.json or a package.json included in the JAR to tell the plugin that it contains client sources which needs to be included in the build as well as what third-party client dependencies the addon has. 

So the addon needs to be a valid WEBJAR right now. 

In the future we could try to lift this restriction but then we would need another way of determining which JARs on the classpath contains client dependencies.

**Comment by ssindelar** [comment]
Just also ran into the problem with the same addon. Any ideas if this is a general problem or is it just the app-layout addon that has this behaviour?

**Comment by johndevs** [comment]
It is a general problem for addons which are not WebJars, i.e they lack a bower.json or package.json and/or don't follow the WebJar folder structure (https://www.webjars.org/contributing).

I guess this could be fixed by the addon author by publishing a webjar compatible version but in the long term I think the plugin could handle non-webjars as well as they are common with server side compositions.

**Comment by johndevs** [comment]
Turns out there was missing support for having folder hierarchies in the static resource directory. All standard Vaadin components only have one level of resources.

**Comment by corinara** [comment]
Hi John,
Do you have an any reference links or doucuments ?
I'd like to let them know about this.

Thanks.
