### ISSUE TITLE
Exit with error code 1 while running `bower` command to resolve deps via `vaadinInstallBowerDependencies`

### ISSUE THREAD

**Issue by christoph-frick** [devsoap/gradle-vaadin-flow#70]
Using M3 I am about to reproduce the recent webinar from Vaadin by adding the `monaco-editor` like this in my `build.gradle`:

```gradle
vaadinClientDependencies {
    bower 'PolymerVis/monaco-editor'
}
```

Running `./gradlew vaadinInstallBowerDependencies` then fails with:

```
> Configure project :
Using Gradle Vaadin Flow Plugin 1.0.0-M3

> Task :vaadinInstallBowerDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vaadinInstallBowerDependencies'.
> Process 'command '$HOME/src/scratchpad/gradle-flow/.gradle/npm/npm-v5.6.0/bin/npm'' finished with non-zero exit value 1
...
```

Checking the generated log in `$HOME/.npm/_logs/...debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '$HOME/src/scratchpad/gradle-flow/.gradle/nodejs/node-v8.11.1-linux-x64/bin/node',
1 verbose cli   '$HOME/src/scratchpad/gradle-flow/.gradle/npm/npm-v5.6.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'bower',
1 verbose cli   'install',
1 verbose cli   '--config.interactive=false' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'prebower', 'bower', 'postbower' ]
5 info lifecycle frontend@1.0.0~prebower: frontend@1.0.0
6 info lifecycle frontend@1.0.0~bower: frontend@1.0.0 
7 verbose lifecycle frontend@1.0.0~bower: unsafe-perm in lifecycle true
8 verbose lifecycle frontend@1.0.0~bower: PATH: $HOME/src/scratchpad/gradle-flow/.gradle/npm/npm-v5.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:$HOME/src/scratchpad/gradle-flow/build/frontend/node_modules/.bin:$HOME/src/scratchpad/gradle-flow/.gradle/npm/npm-v5.6.0/bin:$HOME/src/scratchpad/gradle-flow/.gradle/nodejs/node-v8.11.1-linux-x64/bin:$HOME/bin:$HOME/.sdkman/candidates/visualvm/current/bin:$HOME/.sdkman/candidates/springboot/current/bin:$HOME/.sdkman/candidates/maven/current/bin:$HOME/.sdkman/candidates/lazybones/current/bin:$HOME/.sdkman/candidates/groovy/current/bin:$HOME/.sdkman/candidates/grails/current/bin:$HOME/.sdkman/candidates/gradle/current/bin:$HOME/.sdkman/candidates/asciidoctorj/current/bin:/usr/lib/ccache/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:$HOME/.node/bin
9 verbose lifecycle frontend@1.0.0~bower: CWD: $HOME/src/scratchpad/gradle-flow/build/frontend
10 silly lifecycle frontend@1.0.0~bower: Args: [ '-c', 'bower "install"' ]
11 silly lifecycle frontend@1.0.0~bower: Returned: code: 1  signal: null
12 info lifecycle frontend@1.0.0~bower: Failed to exec bower script
13 verbose stack Error: frontend@1.0.0 bower: `bower "install"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> ($HOME/src/scratchpad/gradle-flow/.gradle/npm/npm-v5.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> ($HOME/src/scratchpad/gradle-flow/.gradle/npm/npm-v5.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid frontend@1.0.0
15 verbose cwd $HOME/src/scratchpad/gradle-flow/build/frontend
16 verbose Linux 4.9.0-6-amd64
17 verbose argv "$HOME/src/scratchpad/gradle-flow/.gradle/nodejs/node-v8.11.1-linux-x64/bin/node" "$HOME/src/scratchpad/gradle-flow/.gradle/npm/npm-v5.6.0/bin/npm" "run" "bower" "install" "--config.interactive=false"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error frontend@1.0.0 bower: `bower "install"`
22 error Exit status 1
23 error Failed at the frontend@1.0.0 bower script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Note that `$HOME` was used to replace the actual dir.

This is the branch failing in the otherwise working project: https://github.com/christoph-frick/try-springboot-vaadin-flow/tree/bower-fails ; feel free to request further information.

**Comment by johndevs** [comment]
The effective ``bower.json`` is generated in ``build/frontend/bower.json`` so we can test it locally. 

If you install npm locally(*sudo apt install npm*) and run "npm run bower install" in the ``build/frontend``-directory what output do you get?

**Comment by johndevs** [comment]
Did a quick test with your test repository, got this:
```
bower PolymerVis/monaco-editor=PolymerVis/monaco-editor#*          resolve https://github.com/michael-golfi/monaco-editor-1.git#*
```
However, there exists no github project at that location so my guess is that the repository has moved but the bower registry has not been updated.

**Comment by christoph-frick** [comment]
Thank you for looking into it.  I'll close, if this is just an upstream error.  I triggered a webjar and see how this comes along.

**Comment by johndevs** [comment]
Bug ticket: https://github.com/PolymerVis/monaco-editor/issues/21

**Comment by johndevs** [comment]
Just note that it might not work out-of-the box with polymer due to:

> Very important note on external dependencies when building/bundling your app
>
> monaco-editor loads most of the required modules dynamically, hence polymer-build will not be able to properly detect these external modules. You will need to manually add bower_components/monaco-editor/node_modules/monaco-editor/min/vs/**/* into the extraDependencies to ensure these modules are exported together.

**Comment by christoph-frick** [comment]
Seems like a picked a particular tricky component just to see how bower deps would work ;)
